=== magneticflux-/qbittorrent-cli/src/QBittorrent.CommandLineInterface/Schemas/colors-schema.json
{
  "$schema": "http://json-schema.org/draft-04/schema",
  "title": "JSON Schema for the qBittorrent CLI color scheme.",
  "type": "object",
  "definitions": {
    "color": {
      "type": "string",
      "enum": [
        "black",
        "blue",
        "cyan",
        "dark-blue",
        "dark-cyan",
        "dark-gray",
        "dark-green",
        "dark-magenta",
        "dark-red",
        "dark-yellow",
        "gray",
        "green",
        "magenta",
        "red",
        "white",
        "yellow",
        "system-bg",
        "system-fg"
      ]
    },
    "colors": {
      "type": "object",
      "properties": {
        "bg": {
          "$ref": "#/definitions/color"
        },
        "fg": {
          "$ref": "#/definitions/color"
        },
        "fg-alt": {
          "$ref": "#/definitions/color"
        }
      }
    }
  },
  "properties": {
    "normal": {
      "$ref": "#/definitions/colors"
    },
    "strong": {
      "$ref": "#/definitions/colors"
    },
    "warning": {
      "$ref": "#/definitions/colors"
    },
    "active": {
      "$ref": "#/definitions/colors"
    },
    "inactive": {
      "$ref": "#/definitions/colors"
    },
    "log": {
      "type": "object",
      "properties": {
        "status-normal": {
          "$ref": "#/definitions/colors"
        },
        "status-info": {
          "$ref": "#/definitions/colors"
        },
        "status-warning": {
          "$ref": "#/definitions/colors"
        },
        "status-critical": {
          "$ref": "#/definitions/colors"
        },
        "timestamp": {
          "$ref": "#/definitions/colors"
        },
        "message": {
          "$ref": "#/definitions/colors"
        }
      }
    },
    "torrent-status": {
      "type": "object",
      "properties": {
        "error": {
          "$ref": "#/definitions/colors"
        },
        "download": {
          "$ref": "#/definitions/colors"
        },
        "upload": {
          "$ref": "#/definitions/colors"
        },
        "paused-download": {
          "$ref": "#/definitions/colors"
        },
        "paused-upload": {
          "$ref": "#/definitions/colors"
        },
        "queued-download": {
          "$ref": "#/definitions/colors"
        },
        "queued-upload": {
          "$ref": "#/definitions/colors"
        },
        "queued-checking": {
          "$ref": "#/definitions/colors"
        },
        "checking-download": {
          "$ref": "#/definitions/colors"
        },
        "checking-upload": {
          "$ref": "#/definitions/colors"
        },
        "checking-resume-data": {
          "$ref": "#/definitions/colors"
        },
        "stalled-download": {
          "$ref": "#/definitions/colors"
        },
        "stalled-upload": {
          "$ref": "#/definitions/colors"
        },
        "forced-download": {
          "$ref": "#/definitions/colors"
        },
        "forced-upload": {
          "$ref": "#/definitions/colors"
        },
        "fetching-metadata": {
          "$ref": "#/definitions/colors"
        },
        "missing-files": {
          "$ref": "#/definitions/colors"
        },
        "allocating": {
          "$ref": "#/definitions/colors"
        },
        "moving": {
          "$ref": "#/definitions/colors"
        },
        "unknown": {
          "$ref": "#/definitions/colors"
        }
      }
    }
  },
  "required": [
    "normal",
    "strong",
    "warning",
    "active",
    "inactive"
  ]
}

=== magneticflux-/qbittorrent-cli/src/QBittorrent.CommandLineInterface/ColorSchemes/light.json
{
  "$schema": "https://raw.githubusercontent.com/fedarovich/qbittorrent-cli/master/src/QBittorrent.CommandLineInterface/Schemas/colors-schema.json",
  "normal": {
    "bg": "system-bg",
    "fg": "system-fg"
  },
  "strong": {
    "bg": "system-bg",
    "fg": "dark-blue",
    "fg-alt": "yellow"
  },
  "warning": {
    "bg": "system-bg",
    "fg": "dark-yellow",
    "fg-alt": "yellow"
  },
  "active": {
    "bg": "system-bg",
    "fg": "dark-green",
    "fg-alt": "cyan"
  },
  "inactive": {
    "bg": "system-bg",
    "fg": "gray",
    "fg-alt": "dark-gray"
  },
  "log": {
    "status-normal": {
      "bg": "system-bg",
      "fg": "dark-green",
      "fg-alt": "green"
    },
    "status-info": {
      "bg": "system-bg",
      "fg": "dark-blue",
      "fg-alt": "blue"
    },
    "status-warning": {
      "bg": "system-bg",
      "fg": "dark-yellow",
      "fg-alt": "yellow"
    },
    "status-critical": {
      "bg": "system-bg",
      "fg": "red",
      "fg-alt": "dark-red"
    },
    "timestamp": {
      "bg": "system-bg",
      "fg": "dark-cyan",
      "fg-alt": "dark-cyan"
    },
    "message": {
      "bg": "system-bg",
      "fg": "black",
      "fg-alt": "dark-gray"
    }
  },
  "torrent-status": {
    "allocating": {
      "bg": "system-bg",
      "fg": "dark-green",
      "fg-alt": "green"
    },
    "checking-download": {
      "bg": "system-bg",
      "fg": "dark-yellow",
      "fg-alt": "yellow"
    },
    "checking-resume-data": {
      "bg": "system-bg",
      "fg": "dark-yellow",
      "fg-alt": "yellow"
    },
    "checking-upload": {
      "bg": "system-bg",
      "fg": "dark-yellow",
      "fg-alt": "yellow"
    },
    "download": {
      "bg": "system-bg",
      "fg": "dark-green",
      "fg-alt": "green"
    },
    "error": {
      "bg": "system-bg",
      "fg": "dark-red",
      "fg-alt": "red"
    },
    "fetching-metadata": {
      "bg": "system-bg",
      "fg": "dark-blue",
      "fg-alt": "blue"
    },
    "forced-download": {
      "bg": "system-bg",
      "fg": "dark-cyan",
      "fg-alt": "cyan"
    },
    "forced-upload": {
      "bg": "system-bg",
      "fg": "dark-cyan",
      "fg-alt": "cyan"
    },
    "missing-files": {
      "bg": "system-bg",
      "fg": "red",
      "fg-alt": "dark-red"
    },
    "moving": {
      "bg": "system-bg",
      "fg": "dark-green",
      "fg-alt": "green"
    },
    "paused-download": {
      "bg": "system-bg",
      "fg": "gray",
      "fg-alt": "dark-gray"
    },
    "paused-upload": {
      "bg": "system-bg",
      "fg": "gray",
      "fg-alt": "dark-gray"
    },
    "queued-checking": {
      "bg": "system-bg",
      "fg": "blue",
      "fg-alt": "dark-blue"
    },
    "queued-download": {
      "bg": "system-bg",
      "fg": "blue",
      "fg-alt": "dark-blue"
    },
    "queued-upload": {
      "bg": "system-bg",
      "fg": "blue",
      "fg-alt": "dark-blue"
    },
    "stalled-download": {
      "bg": "system-bg",
      "fg": "dark-yellow",
      "fg-alt": "gray"
    },
    "stalled-upload": {
      "bg": "system-bg",
      "fg": "dark-yellow",
      "fg-alt": "gray"
    },
    "unknown": {
      "bg": "system-bg",
      "fg": "dark-magenta",
      "fg-alt": "magenta"
    },
    "upload": {
      "bg": "system-bg",
      "fg": "dark-green",
      "fg-alt": "green"
    }
  }
}

=== magneticflux-/qbittorrent-cli/src/QBittorrent.CommandLineInterface/ColorSchemes/dark.json
{
  "$schema": "https://raw.githubusercontent.com/fedarovich/qbittorrent-cli/master/src/QBittorrent.CommandLineInterface/Schemas/colors-schema.json",
  "normal": {
    "bg": "system-bg",
    "fg": "system-fg"
  },
  "strong": {
    "bg": "system-bg",
    "fg": "yellow",
    "fg-alt": "dark-blue"
  },
  "warning": {
    "bg": "system-bg",
    "fg": "yellow",
    "fg-alt": "dark-yellow"
  },
  "active": {
    "bg": "system-bg",
    "fg": "green",
    "fg-alt": "dark-cyan"
  },
  "inactive": {
    "bg": "system-bg",
    "fg": "dark-gray",
    "fg-alt": "gray"
  },
  "log": {
    "status-normal": {
      "bg": "system-bg",
      "fg": "green",
      "fg-alt": "dark-green"
    },
    "status-info": {
      "bg": "system-bg",
      "fg": "blue",
      "fg-alt": "dark-blue"
    },
    "status-warning": {
      "bg": "system-bg",
      "fg": "yellow",
      "fg-alt": "dark-yellow"
    },
    "status-critical": {
      "bg": "system-bg",
      "fg": "dark-red",
      "fg-alt": "red"
    },
    "timestamp": {
      "bg": "system-bg",
      "fg": "white",
      "fg-alt": "dark-gray"
    },
    "message": {
      "bg": "system-bg",
      "fg": "gray",
      "fg-alt": "dark-gray"
    }
  },
  "torrent-status": {
    "allocating": {
      "bg": "system-bg",
      "fg": "green",
      "fg-alt": "dark-green"
    },
    "checking-download": {
      "bg": "system-bg",
      "fg": "yellow",
      "fg-alt": "dark-yellow"
    },
    "checking-resume-data": {
      "bg": "system-bg",
      "fg": "yellow",
      "fg-alt": "dark-yellow"
    },
    "checking-upload": {
      "bg": "system-bg",
      "fg": "yellow",
      "fg-alt": "dark-yellow"
    },
    "download": {
      "bg": "system-bg",
      "fg": "green",
      "fg-alt": "dark-green"
    },
    "error": {
      "bg": "system-bg",
      "fg": "red",
      "fg-alt": "dark-red"
    },
    "fetching-metadata": {
      "bg": "system-bg",
      "fg": "blue",
      "fg-alt": "dark-blue"
    },
    "forced-download": {
      "bg": "system-bg",
      "fg": "cyan",
      "fg-alt": "dark-cyan"
    },
    "forced-upload": {
      "bg": "system-bg",
      "fg": "cyan",
      "fg-alt": "dark-cyan"
    },
    "missing-files": {
      "bg": "system-bg",
      "fg": "red",
      "fg-alt": "dark-red"
    },
    "moving": {
      "bg": "system-bg",
      "fg": "green",
      "fg-alt": "dark-green"
    },
    "paused-download": {
      "bg": "system-bg",
      "fg": "dark-gray",
      "fg-alt": "gray"
    },
    "paused-upload": {
      "bg": "system-bg",
      "fg": "dark-gray",
      "fg-alt": "gray"
    },
    "queued-checking": {
      "bg": "system-bg",
      "fg": "dark-blue",
      "fg-alt": "blue"
    },
    "queued-download": {
      "bg": "system-bg",
      "fg": "dark-blue",
      "fg-alt": "blue"
    },
    "queued-upload": {
      "bg": "system-bg",
      "fg": "dark-blue",
      "fg-alt": "blue"
    },
    "stalled-download": {
      "bg": "system-bg",
      "fg": "dark-yellow",
      "fg-alt": "gray"
    },
    "stalled-upload": {
      "bg": "system-bg",
      "fg": "dark-yellow",
      "fg-alt": "gray"
    },
    "unknown": {
      "bg": "system-bg",
      "fg": "magenta",
      "fg-alt": "dark-magenta"
    },
    "upload": {
      "bg": "system-bg",
      "fg": "green",
      "fg-alt": "dark-green"
    }
  }
}
